global:
  resolve_timeout: 3m

time_intervals:
  - name: work_days
    time_intervals:
      - times:
          - start_time: 09:00
            end_time: 17:00
      - weekdays: ['monday:friday']

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 3m
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
    - match:
        severity: warning
      receiver: 'warning-receiver'
      active_time_intervals:
        - work_days

receivers:
  - name: 'default-receiver'
    telegram_configs:
        - send_resolved: true
          api_url: 'https://api.telegram.org'
          bot_token: 5842289888:AAH0QCW5H-jC_0vNPreeg6ApUuLFpUIe5qw
          chat_id: 753253858
          message: "Alertname: {{ .GroupLabels.alertname }}\n
                    Severity: {{ .CommonLabels.severity }}\n
                    {{ range .Alerts }}{{ .Annotations.description }}\n
                    {{ end }}"

  - name: 'critical-receiver'
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token: 5842289888:AAH0QCW5H-jC_0vNPreeg6ApUuLFpUIe5qw
        chat_id: 753253858
        message: "Alertname: {{ .GroupLabels.alertname }}\n
                  Severity: {{ .CommonLabels.severity }}\n
                  {{ range .Alerts }}{{ .Annotations.description }}\n
                  {{ end }}"

  - name: 'warning-receiver'
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token: 5842289888:AAH0QCW5H-jC_0vNPreeg6ApUuLFpUIe5qw
        chat_id: 753253858
        message: "Alertname: {{ .GroupLabels.alertname }}\n
                  Severity: {{ .CommonLabels.severity }}\n
                  {{ range .Alerts }}{{ .Annotations.description }}\n
                  {{ end }}"
