filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        format: docker
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

output.logstash:
  hosts: [ "logstash:5044" ]
