global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/alerts.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'oncall'
    scrape_interval: 15s
    static_configs:
      - targets: ['oncall-web:8081']

  - job_name: 'blackbox-http_2xx'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - oncall-web:8080
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'duty-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['duty-exporter:8090']
